"""
Django settings for DivertyCam project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-61vr-l6&i^xa6pd6_294*7ke2xswq=v(1aljvsx2kuv_yqg9s#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['6501-191-95-49-121.ngrok-free.app', '127.0.0.1', 'localhost', '192.168.1.4']

FACEBOOK_ACCESS_TOKEN = "EAAQdEZB18le8BOyh5B4DMPTjx74qEq4mvYLDuhjiI4ytyYrzMn8dYTy0uZCOiZC1CABiZCbTtDFD4ZAgvdNMwfBXgl5cDJofwgghxblGJJPEdTZB0FgAz3N09SDntgDNZAzmI2di1fh9vVAnXsSqD6AsjVmdBXeCNODEFT3t1ZCx5J7yg97QUetZB9puQaS7uvcNpDMk5NoT2oA4zZCCHdIKziaCGTujBB"

FACEBOOK_PAGE_ID = "612248578630248"


# Permitir credenciales
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# Métodos permitidos
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")






# Application definition

INSTALLED_APPS = [
    'usuarios',
    'jazzmin',
    'corsheaders',
    'multiselectfield',
    'widget_tweaks',
    'requests',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_TRUSTED_ORIGINS = [
   # "https://6501-191-95-49-121.ngrok-free.app",
    "http://127.0.0.1:8000",  # Para pruebas locales
    "http://localhost:8000",
]

ROOT_URLCONF = 'DivertyCam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DivertyCam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ProyectoDB',  # El nombre de la base de datos creada
        'USER': 'postgres',  # El nombre de usuario de PostgreSQL
        'PASSWORD': '123456',  # La contraseña del usuario
        'HOST': 'localhost',  # El host donde está corriendo PostgreSQL
        'PORT': '5432',  # El puerto por defecto de PostgreSQL
    }
}

AUTH_USER_MODEL = 'usuarios.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
     {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Para archivos globales
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap5'


JAZZMIN_SETTINGS={
    "site_title":"DivertyCam",
    "site_header":"DivertyCam",
    "site_brand":"DivertyCam",
    
    "show_ui_builder":True,
     "topmenu_links": [
        {"name": "Inicio", "url": "/", "new_window": False, "icon": "fas fa-home"},
        
    ],
    
    
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-navy",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-purple",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lux",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

#SMTP configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))  # Convierte a entero
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"  # Convierte a booleano
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Aumentar el límite de tamaño para cargas de datos (20MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB en bytes

# También ajustar el tamaño máximo de archivos si es necesario
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB en bytes

# Crear directorio temp_usb si no existe
TEMP_USB_DIR = os.path.join(MEDIA_ROOT, 'temp_usb')
if not os.path.exists(TEMP_USB_DIR):
    os.makedirs(TEMP_USB_DIR, exist_ok=True)

# ===========================================
# Configuración de ADB para WhatsApp System
# ===========================================

# Ruta a ADB (Android Debug Bridge)
ADB_PATH = r'C:\Users\DELL\AppData\Local\Android\Sdk\platform-tools\adb.exe'

# Configuración USB para transferencias
USB_TRANSFER_CONFIG = {
    'DEVICE_FOLDER': '/sdcard/photobooth/',
    'TEMP_FOLDER': os.path.join(MEDIA_ROOT, 'temp_usb'),
    'CONNECTION_TIMEOUT': 10,
    'TRANSFER_TIMEOUT': 30,
    'MAX_RETRIES': 3,
}

# Crear directorio temporal si no existe
TEMP_USB_DIR = os.path.join(MEDIA_ROOT, 'temp_usb')
os.makedirs(TEMP_USB_DIR, exist_ok=True)

# Logging para el sistema de transferencia
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'usb_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'whatsapp_transfer.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'usuarios.utils.usb_communication': {
            'handlers': ['usb_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Crear directorio de logs si no existe
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
